/**
 * The Lucide icons the viewer asks for by Obsidian icon id. Importing them by
 * name (rather than the whole `icons` map) keeps the bundle small.
 */
import {
  Blend,
  Box,
  BoxSelect,
  Camera,
  ChevronDown,
  ChevronRight,
  ChevronsDownUp,
  ChevronsUpDown,
  Download,
  Eye,
  EyeOff,
  Focus,
  FolderOpen,
  Footprints,
  Grid,
  Info,
  Layers,
  Link,
  ListTree,
  Magnet,
  Maximize,
  MessagesSquare,
  Milestone,
  Monitor,
  Moon,
  Move3d,
  Pin,
  RefreshCw,
  RotateCcw,
  RotateCw,
  Ruler,
  Scissors,
  Settings,
  Share,
  Smartphone,
  StickyNote,
  Sun,
  SunMoon,
  Trash,
  Trash2,
  X,
} from "lucide";
import type { IconNode } from "lucide";

export const ICONS: Record<string, IconNode> = {
  blend: Blend,
  box: Box,
  "box-select": BoxSelect,
  camera: Camera,
  "chevron-down": ChevronDown,
  "chevron-right": ChevronRight,
  "chevrons-down-up": ChevronsDownUp,
  "chevrons-up-down": ChevronsUpDown,
  download: Download,
  eye: Eye,
  "eye-off": EyeOff,
  focus: Focus,
  "folder-open": FolderOpen,
  footprints: Footprints,
  grid: Grid,
  info: Info,
  layers: Layers,
  link: Link,
  "list-tree": ListTree,
  magnet: Magnet,
  maximize: Maximize,
  "messages-square": MessagesSquare,
  milestone: Milestone,
  monitor: Monitor,
  moon: Moon,
  "move-3d": Move3d,
  pin: Pin,
  "refresh-cw": RefreshCw,
  "rotate-ccw": RotateCcw,
  "rotate-cw": RotateCw,
  ruler: Ruler,
  scissors: Scissors,
  settings: Settings,
  share: Share,
  smartphone: Smartphone,
  "sticky-note": StickyNote,
  sun: Sun,
  "sun-moon": SunMoon,
  trash: Trash,
  "trash-2": Trash2,
  x: X,
};
